# .github/workflows/run_pipeline.yml

name: Run Document Auth Pipeline
on:
  workflow_dispatch:  # manual trigger only

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies & package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Prepare data directories
        run: |
          mkdir -p data/input data/output

      - name: Run pipeline
        run: |
          docauth run --input-dir data/input --output-dir data/output
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          GCP_PROJECT_ID:           ${{ secrets.GCP_PROJECT_ID }}
          GCP_LOCATION:             ${{ secrets.GCP_LOCATION }}
          GCP_PROCESSOR_ID:         ${{ secrets.GCP_PROCESSOR_ID }}
          GEMINI_ENDPOINT_URL:      ${{ secrets.GEMINI_ENDPOINT_URL }}
          GEMINI_API_KEY:           ${{ secrets.GEMINI_API_KEY }}
